version: "3.9"

services:
  mongodb-dev:
    image: mongo:6.0
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: [ "bash", "-c", "yarn start" ]
    environment:
      - PORT=8090
      - DATABASE_TEST=mongodb://mongodb-dev:27017/ubs
      - NODE_ENV=dev
      - JWT_SECRET=DaoxGNGbKX9fPhKg3G9LStWEsAG2C6
      - JWT_EXPIRES_IN=90d
      - JWT_COOKIE_EXPIRES_IN=90
    ports:
      - "8090:8090"
    depends_on:
      - mongodb-dev
    restart: always
    volumes:
      - ./backend:/backend
    links:
      - mongodb-dev

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: [ "bash", "-c", "yarn start" ]
    environment:
      - PORT=3002
      - BACKEND_PORT=8090
    ports:
      - "80:3002"
    depends_on:
      - backend-dev
    restart: always
    volumes:
      - ./frontend:/frontend
